### PR TITLE
[openApiDiff.ts] Replace `exec` with `execFile`

### LINKED ISSUE #254: Errors on fresh install of oad
Environment:
- fresh install of `oad` from `npm install -g oav`. I've never used it before. Version installed was `0.1.9`.
- Windows 11
- .NET version 6.0.402

When I run `oad compare my-old-spec.json my-new-spec.json` as per the instructions, I get the file not found errors. If I manually create these files out of curiosity, I still get an error.

```
# Initial error
> oad compare ..\..\stable\2022-01-01\redisenterprise.json .\redisenterprise.json
File "C:\Users\jantache\AppData\Local\Temp\old.json" not found.

# Error after manually creating old.json
> oad compare ..\..\stable\2022-01-01\redisenterprise.json .\redisenterprise.json
File "C:\Users\jantache\AppData\Local\Temp\new.json" not found.

# Error after manually creating both new.json and old.json
> oad compare ..\..\stable\2022-01-01\redisenterprise.json .\redisenterprise.json
Error: Command failed: dotnet C:\Program Files\WindowsPowerShell\Modules\nvm\2.5.1\vs\v14.18.1\node_modules\oad\lib\dlls\OpenApiDiff.dll -o C:\Users\jantache\AppData\Local\Temp\old.json -n C:\Users\jantache\AppData\Local\Temp\new.json -JsonValidationMessages
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-C:\Program does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'dotnet C:\\Program Files\\WindowsPowerShell\\Modules\\nvm\\2.5.1\\vs\\v14.18.1\\node_modules\\oad\\lib\\dlls\\OpenApiDiff.dll -o C:\\Users\\jantache\\AppData\\Local\\Temp\\old.json -n C:\\Users\\jantache\\AppData\\Local\\Temp\\new.json -JsonValidationMessages'
}
```

### PR DESCRIPTION
**Pull request by mikeharder**
- fixes #254

### CODE REVIEW

File: src/lib/validators/openApiDiff.ts [hunk 1]
```diff
@@ -2,23 +2,21 @@
 // Licensed under the MIT License. See License.txt in the project root for license information.
 
 import * as asyncFs from "@ts-common/fs"
-import * as jsonParser from "@ts-common/json-parser"
```
Comment (mikeharder) [inline src/lib/validators/openApiDiff.ts:5]: unrelated unused import

File: CHANGELOG.md [hunk 2]
```diff
@@ -3,6 +3,7 @@
 ## 0.12.0 2025-08-29
 
 - replaced dependency 'request' with built-in fetch() API
+- replaced child_process.exec with child_proces.execFile
```
Comment (mikeharder) [inline CHANGELOG.md:6]:
```suggestion
- replaced child_process.exec() with execFile()
```

File: src/lib/validators/openApiDiff.ts [hunk 3]
```diff
@@ -250,16 +226,24 @@ export class OpenApiDiff {
...
-    const autoRestCmd = tagName
-      ? `${this.autoRestPath()} ${escapeShellArg(swaggerPath)} --v2 --tag=${escapeShellArg(tagName)} --output-artifact=swagger-document.json` +
-        ` --output-artifact=swagger-document.map --output-file=${escapeShellArg(outputFileName)} --output-folder=${escapeShellArg(outputFolder)}`
-      : `${this.autoRestPath()} --v2 --input-file=${escapeShellArg(swaggerPath)} --output-artifact=swagger-document.json` +
-        ` --output-artifact=swagger-document.map --output-file=${escapeShellArg(outputFileName)} --output-folder=${escapeShellArg(outputFolder)}`
 
-    log.debug(`Executing: "${autoRestCmd}"`)
+    const { file: autoRestFile, args: autoRestArgs } = this.autoRestFileArgs()
+
+    const swaggerArgs = tagName ? [swaggerPath, `--tag=${tagName}`] : [`--input-file=${swaggerPath}`]
```
Comment (mikeharder) [inline src/lib/validators/openApiDiff.ts:232]: Do we still need to quote/escape any of the variable strings used as values in params like `--foo=${bar}`?  Or would a param like `--foo=C:\folder with spaces\` work without quoting, since it's not going through the shell?

**Review by raych1 — APPROVED** [review]
